---
layout: cv
title: Taylor Spurling's Resume
---
# Taylor Spurling
Data Analyst

<div id="webaddress">
<a href="https://www.linkedin.com/in/taylorspurling/">LinkedIn Profile</a>
</div>


- Phone: 812.371.1447
- Email: taylorspurling@gmail.com

## Education

- **Brigham Young University - Idaho**
  - Bachelor of Science in Business Analytics
  - Looking to go into Data Analysis
  - Expert knowledge of Microsoft Office (Excel, Word)
  - Experience with Data Visualization Programs (Tableau, Power BI/DAX)
  - Growing understanding of Python, SQL, and R

## Experience

### Brigham Young University - Idaho
- **Assistant of LMS and Academic Technology Support**
  - Rexburg, Idaho
  - April 2020 - July 2024
  - Provided specialized in-person, email, and phone training and support to over 300 faculty members
  - Dealt with a variety of programs such as Canvas, Microsoft & Google Suite, Zoom, and Perusall

### Republic Airways
- **Strategic Operations Intern**
  - Indianapolis, Indiana
  - May 2023 - August 2023
  - Automized a data reconciliation process that originally took 20+ minutes down to less than 5 minutes
  - Validated company data with many different partners through robust Microsoft Excel formulas
  - Dashboard creation through Power BI

### The Church of Jesus Christ of Latter-day Saints
- **Full-Time Volunteer Representative**
  - Guided others to set weekly goals and determine plans to accomplish these goals
  - Served 85+ hours a week
  - Led weekly and monthly training for 20-30 volunteers
  - Became fluent in Cambodian (Khmer)

### Adidas
- **Supervisor/Sales Associate**
  - Phnom Penh, Cambodia (January 2018 - February 2020)
  - Edinburg, Indiana (October 2014 - August 2017)
  - Greeted and interacted with customers by answering questions, improving visual merchandising, and providing customer service
  - Operated and trained others on cash registers, managed transactions, and balanced cash drawers
  - Oversaw success of 30+ employees by analyzing daily sales goals and teaching sales tactics

## Applicable Coursework

- Financial & Managerial Accounting
- Spreadsheet Analysis for Business
- Database Design & Development
- Economic Principles Micro & Macro



<!-- ### Footer

Last updated: May 2013 -->